import { IBank, IUser } from "../Types/usermanagementTypes";

export const mockSummary = {
  users: 120,
  bankAdmin: 15,
  superAdmin: 18,
};

export const mockBanks: IBank[] = [
  { id: 1, name: "Access Bank", code: "044", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Main Branch", isActive: true, bankAdmins: [{ id: 1, username: "admin1", email: "admin1@access.com", firstName: "John", lastName: "Doe", active: true }] },
  { id: 2, name: "GTBank", code: "058", address: "Abuja, Nigeria", image: null, location: "Abuja", branch: "Central Branch", isActive: true, bankAdmins: [{ id: 2, username: "admin2", email: "admin2@gtbank.com", firstName: "Jane", lastName: "Smith", active: true }] },
  { id: 3, name: "First Bank", code: "011", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Victoria Island", isActive: true, bankAdmins: [{ id: 3, username: "admin3", email: "admin3@firstbank.com", firstName: "Michael", lastName: "Johnson", active: true }] },
  { id: 4, name: "UBA", code: "033", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Marina", isActive: false, bankAdmins: [{ id: 4, username: "admin4", email: "admin4@uba.com", firstName: "Sarah", lastName: "Williams", active: false }] },
  { id: 5, name: "Zenith Bank", code: "057", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Ikeja", isActive: true, bankAdmins: [{ id: 5, username: "admin5", email: "admin5@zenith.com", firstName: "David", lastName: "Brown", active: true }] },
  { id: 6, name: "Ecobank", code: "050", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Lekki", isActive: true, bankAdmins: [{ id: 6, username: "admin6", email: "admin6@ecobank.com", firstName: "Emily", lastName: "Davis", active: true }] },
  { id: 7, name: "Fidelity Bank", code: "070", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Surulere", isActive: false, bankAdmins: [] },
  { id: 8, name: "Sterling Bank", code: "232", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Yaba", isActive: true, bankAdmins: [{ id: 7, username: "admin7", email: "admin7@sterling.com", firstName: "Chris", lastName: "Miller", active: true }] },
  { id: 9, name: "Union Bank", code: "032", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Ikoyi", isActive: true, bankAdmins: [{ id: 8, username: "admin8", email: "admin8@union.com", firstName: "Amanda", lastName: "Wilson", active: true }] },
  { id: 10, name: "Stanbic IBTC", code: "221", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "VI", isActive: true, bankAdmins: [{ id: 9, username: "admin9", email: "admin9@stanbic.com", firstName: "Robert", lastName: "Taylor", active: true }] },
  { id: 11, name: "Wema Bank", code: "035", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Ojuelegba", isActive: false, bankAdmins: [] },
  { id: 12, name: "Polaris Bank", code: "076", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Apapa", isActive: true, bankAdmins: [{ id: 10, username: "admin10", email: "admin10@polaris.com", firstName: "Lisa", lastName: "Anderson", active: true }] },
  { id: 13, name: "Keystone Bank", code: "082", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Festac", isActive: true, bankAdmins: [{ id: 11, username: "admin11", email: "admin11@keystone.com", firstName: "James", lastName: "Thomas", active: true }] },
  { id: 14, name: "FCMB", code: "214", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Allen", isActive: true, bankAdmins: [{ id: 12, username: "admin12", email: "admin12@fcmb.com", firstName: "Patricia", lastName: "Jackson", active: true }] },
  { id: 15, name: "Heritage Bank", code: "030", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Ogba", isActive: false, bankAdmins: [] },
  { id: 16, name: "Providus Bank", code: "101", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Maryland", isActive: true, bankAdmins: [{ id: 13, username: "admin13", email: "admin13@providus.com", firstName: "Daniel", lastName: "White", active: true }] },
  { id: 17, name: "Titan Trust Bank", code: "102", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Ilupeju", isActive: true, bankAdmins: [{ id: 14, username: "admin14", email: "admin14@titan.com", firstName: "Nancy", lastName: "Harris", active: true }] },
  { id: 18, name: "Globus Bank", code: "103", address: "Lagos, Nigeria", image: null, location: "Lagos", branch: "Oshodi", isActive: true, bankAdmins: [{ id: 15, username: "admin15", email: "admin15@globus.com", firstName: "Kevin", lastName: "Martin", active: true }] },
];

// Bank Admins - only BANK_ADMIN role
export const mockBankAdmins: IUser[] = [
  { id: 1, firstName: "John", lastName: "Doe", username: "johndoe", email: "john.doe@access.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 1, name: "Access Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-01-15", updatedAt: "2025-01-15", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 2, firstName: "Jane", lastName: "Smith", username: "janesmith", email: "jane.smith@gtbank.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 2, name: "GTBank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-02-10", updatedAt: "2025-02-10", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 3, firstName: "Michael", lastName: "Johnson", username: "michaelj", email: "michael.j@firstbank.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 3, name: "First Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: false, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-03-05", updatedAt: "2025-03-05", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 4, firstName: "Sarah", lastName: "Williams", username: "sarahw", email: "sarah.w@uba.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 4, name: "UBA", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-03-20", updatedAt: "2025-03-20", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 5, firstName: "David", lastName: "Brown", username: "davidb", email: "david.b@zenith.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 5, name: "Zenith Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-04-12", updatedAt: "2025-04-12", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 6, firstName: "Emily", lastName: "Davis", username: "emilyd", email: "emily.d@ecobank.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 6, name: "Ecobank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-05-08", updatedAt: "2025-05-08", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 7, firstName: "Chris", lastName: "Miller", username: "chrism", email: "chris.m@sterling.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 8, name: "Sterling Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: false, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-06-01", updatedAt: "2025-06-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 8, firstName: "Amanda", lastName: "Wilson", username: "amandaw", email: "amanda.w@union.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 9, name: "Union Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-06-15", updatedAt: "2025-06-15", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 9, firstName: "Robert", lastName: "Taylor", username: "robertt", email: "robert.t@stanbic.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 10, name: "Stanbic IBTC", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-07-10", updatedAt: "2025-07-10", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 10, firstName: "Lisa", lastName: "Anderson", username: "lisaa", email: "lisa.a@polaris.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 12, name: "Polaris Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-08-05", updatedAt: "2025-08-05", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 11, firstName: "James", lastName: "Thomas", username: "jamest", email: "james.t@keystone.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 13, name: "Keystone Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: false, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-08-20", updatedAt: "2025-08-20", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 12, firstName: "Patricia", lastName: "Jackson", username: "patriciaj", email: "patricia.j@fcmb.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 14, name: "FCMB", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-09-10", updatedAt: "2025-09-10", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 13, firstName: "Daniel", lastName: "White", username: "danielw", email: "daniel.w@providus.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 16, name: "Providus Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-10-01", updatedAt: "2025-10-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 14, firstName: "Nancy", lastName: "Harris", username: "nancyh", email: "nancy.h@titan.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 17, name: "Titan Trust Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-10-15", updatedAt: "2025-10-15", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 15, firstName: "Kevin", lastName: "Martin", username: "kevinm", email: "kevin.m@globus.com", role: { id: 2, name: "BANK_ADMIN" }, tenant: { id: 18, name: "Globus Bank", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-11-01", updatedAt: "2025-11-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
];

// ISW Admins - only SUPER_ADMIN role
export const mockIswAdmins: IUser[] = [
  { id: 101, firstName: "Anthony", lastName: "Obi", username: "anthonyobi", email: "anthony.obi@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-01-01", updatedAt: "2025-01-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 102, firstName: "Grace", lastName: "Adeyemi", username: "graceadeyemi", email: "grace.adeyemi@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-01-10", updatedAt: "2025-01-10", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 103, firstName: "Chinedu", lastName: "Eze", username: "chinedueze", email: "chinedu.eze@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: false, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-02-05", updatedAt: "2025-02-05", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 104, firstName: "Funke", lastName: "Balogun", username: "funkebalogun", email: "funke.balogun@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-02-20", updatedAt: "2025-02-20", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 105, firstName: "Emeka", lastName: "Nwosu", username: "emekanwosu", email: "emeka.nwosu@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-03-15", updatedAt: "2025-03-15", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 106, firstName: "Aisha", lastName: "Mohammed", username: "aishamohammed", email: "aisha.mohammed@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-04-01", updatedAt: "2025-04-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 107, firstName: "Tunde", lastName: "Bakare", username: "tundebakare", email: "tunde.bakare@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: false, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-04-20", updatedAt: "2025-04-20", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 108, firstName: "Ngozi", lastName: "Okafor", username: "ngoziokafor", email: "ngozi.okafor@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-05-10", updatedAt: "2025-05-10", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 109, firstName: "Yusuf", lastName: "Abdullahi", username: "yusufabdullahi", email: "yusuf.abdullahi@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-06-01", updatedAt: "2025-06-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 110, firstName: "Blessing", lastName: "Udo", username: "blessingudo", email: "blessing.udo@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-06-20", updatedAt: "2025-06-20", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 111, firstName: "Obinna", lastName: "Chukwu", username: "obinnachukwu", email: "obinna.chukwu@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: false, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-07-15", updatedAt: "2025-07-15", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 112, firstName: "Adaeze", lastName: "Ibe", username: "adaezeibe", email: "adaeze.ibe@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-08-01", updatedAt: "2025-08-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 113, firstName: "Kola", lastName: "Adesanya", username: "kolaadesanya", email: "kola.adesanya@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-08-20", updatedAt: "2025-08-20", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 114, firstName: "Hauwa", lastName: "Suleiman", username: "hauwasuleiman", email: "hauwa.suleiman@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-09-10", updatedAt: "2025-09-10", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 115, firstName: "Victor", lastName: "Ogbu", username: "victorogbu", email: "victor.ogbu@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-10-01", updatedAt: "2025-10-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 116, firstName: "Chioma", lastName: "Nwankwo", username: "chiomanwankwo", email: "chioma.nwankwo@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: false, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-10-20", updatedAt: "2025-10-20", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 117, firstName: "Ahmed", lastName: "Ibrahim", username: "ahmedibrahim", email: "ahmed.ibrahim@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-11-10", updatedAt: "2025-11-10", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
  { id: 118, firstName: "Sandra", lastName: "Emenike", username: "sandraemenike", email: "sandra.emenike@isw.com", role: { id: 1, name: "SUPER_ADMIN" }, tenant: { id: 100, name: "ISW", active: true, createdAt: "2025-01-01", updatedAt: "2025-01-01" }, active: true, locked: false, firstLogin: false, userActivated: true, createdAt: "2025-12-01", updatedAt: "2025-12-01", credentialsNonExpired: true, accountNonExpired: true, accountNonLocked: true },
];